(() => {
  'use strict';
  const allWorks=window.PORTFOLIO_WORKS||[];
  const works=allWorks.filter(w=>!['offline','retouch'].includes(w.type));
  const byKey=Object.fromEntries(works.map(w=>[w.key,w]));
  const names={toothbrushGlobal:'덴클 글로벌 칫솔 상세페이지',granuleOfficial:'덴클 그래뉼 치약 · 공식몰',granule:'덴클 그래뉼 치약 · 카카오 선물하기',connectKinloch:'커넥트킨록 상세페이지 리뉴얼',edinburghClub:'에든버러클럽 니트웨어 상세페이지',pinkHaloTintLaunch:'뷰티 브랜드 제품 런칭 키비주얼',visualAi13:'수분 앰플 디지털 광고',instagramFeed:'덴클 인스타그램 피드',kinlochMoodBoard:'커넥트킨록 브랜드 무드보드',edinburghCardNews:'에든버러클럽 겨울 오피스룩',edinburghEventInfo:'에든버러클럽 클리어런스 콘텐츠',influencerSponsorship:'인플루언서 스타일링 콘텐츠',summerBanner:'에든버러클럽 여름 프로모션',seasonOffBanner:'에든버러클럽 시즌오프 배너',chuseokBigSale:'킨록 추석 빅세일 배너',summerEvent:'덴클 여름 프로모션 페이지',birthdayEvent:'덴클 10주년 프로모션',brochureGranule:'덴클 특허 기술 브로슈어',brochureToothbrush:'덴클 칫솔 브로슈어',productIntro:'덴클 그래뉼 제품소개서',edinburghCompanyDeck:'에든버러클럽 브랜드 소개서',connectKinlochProposal:'커넥트킨록 사업제안서'};
  const typeNames={detail:'상세페이지',sns:'SNS',event:'프로모션',visual:'AI 이미지 생성',print:'인쇄물'};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const plain=value=>String(value??'').replace(/<[^>]*>/g,'');
  const title=w=>names[w.key]||w.title;
  let activeFilter='all',shown=6;
  const grid=document.getElementById('archive-grid'),more=document.getElementById('load-more');
  function filteredWorks(){return works.filter(w=>activeFilter==='all'||w.type===activeFilter);}
  function renderArchive(){const filtered=filteredWorks();grid.innerHTML=filtered.slice(0,shown).map(w=>`<a class="archive-item" href="#project/${esc(w.key)}"><div class="archive-picture"><img src="${esc(w.image)}" alt="${esc(w.alt||title(w))}" loading="lazy"></div><div class="archive-kind"><span>${esc(typeNames[w.type])}</span>${w.personal?'<span class="personal">개인 프로젝트'+(w.type==='visual'?' · AI':'')+'</span>':''}</div><h3>${esc(title(w))}</h3></a>`).join('');document.querySelector('.archive-count').textContent=`${filtered.length} WORKS`;more.hidden=shown>=filtered.length;more.innerHTML=`작업 더 보기 (${Math.max(0,filtered.length-shown)}) <span aria-hidden="true">+</span>`;}
  document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;shown=6;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderArchive();}));
  more.addEventListener('click',()=>{const previous=shown;shown+=6;renderArchive();grid.children[previous]?.focus({preventScroll:true});});renderArchive();

  const dialog=document.getElementById('project-dialog'),content=document.getElementById('project-content');
  const viewer=document.getElementById('image-viewer'),viewerImage=document.getElementById('viewer-image'),zoomButton=document.getElementById('zoom-image');
  let imageTrigger=null;
  document.addEventListener('click',e=>{const link=e.target.closest('a[data-enlarge]');if(!link)return;e.preventDefault();imageTrigger=link;viewerImage.src=link.href;viewerImage.alt=(link.querySelector('img')||link.closest('.study-panel, .detail-section')?.querySelector('img'))?.alt||'작업 이미지';viewer.classList.remove('is-zoomed');zoomButton.textContent='더 확대';zoomButton.setAttribute('aria-pressed','false');document.body.classList.add('modal-open');viewer.showModal();viewer.scrollTop=0;viewer.querySelector('.image-viewer-canvas').scrollTo(0,0);});
  document.getElementById('close-image').addEventListener('click',()=>viewer.close());
  document.getElementById('back-image').addEventListener('click',()=>viewer.close());
  viewer.addEventListener('cancel',e=>{e.preventDefault();viewer.close();});
  viewer.addEventListener('close',()=>{viewerImage.removeAttribute('src');if(!dialog.open)document.body.classList.remove('modal-open');imageTrigger?.focus({preventScroll:true});});
  zoomButton.addEventListener('click',()=>{const zoomed=viewer.classList.toggle('is-zoomed');zoomButton.textContent=zoomed?'화면에 맞추기':'더 확대';zoomButton.setAttribute('aria-pressed',String(zoomed));});
  let returnHash='#selected',returnFocus=null,openedFromPage=false;
  const image=(src,alt,caption='')=>`<div class="large-work"><img src="${esc(src)}" alt="${esc(alt)}" loading="lazy"></div><p class="image-caption">${esc(caption)} <a href="${esc(src)}" data-enlarge>이미지 크게 보기 ↗</a></p>`;
  const section=(heading,body)=>`<section class="detail-section"><h2>${esc(heading)}</h2>${body}</section>`;
  const facts=items=>`<dl class="detail-facts">${items.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`;
  const head=(category,heading,summary)=>`<header class="detail-header"><span class="eyebrow">${esc(category)}</span><h1 id="detail-title" tabindex="-1">${esc(heading)}</h1><p>${esc(plain(summary)).replace(/\n/g,'<br>')}</p></header>`;
  function channelStudy(){const a=byKey.granuleOfficial,b=byKey.granule;return head('COMMERCE / CHANNEL DESIGN · 실무 프로젝트','채널이 달라지면, 디자인의 언어도 달라집니다.','덴클 그래뉼 치약을 공식몰과 카카오 선물하기에 맞춰 다르게 구성했습니다.\n제품을 충분히 검토하는 고객과 선물의 매력을 빠르게 판단하는 고객, 각각의 탐색 흐름에 맞춘 상세페이지입니다.')+facts([['프로젝트','덴클 그래뉼 치약 상세페이지'],['담당','정보 구조 · 비주얼 · 레이아웃 디자인'],['참여 범위','디자인 100% (텍스트 제외)']])+section('채널이 달라지면, 설득의 순서도 달라집니다.',`<div class="study-two"><article class="study-panel"><span class="eyebrow">01 / OFFICIAL STORE</span><h3>신뢰를 쌓아가는 꼼꼼한 페이지</h3><p>'가루 치약'이라는 낯선 고가 제품인 만큼, 고객에게 확신을 주는 것이 가장 중요했습니다.<br>화려함보다는 브랜드의 전문성이 돋보이도록 특허 기술과 성분 이야기를 깊이 있게 다뤘습니다.<br>고객이 차근차근 제품의 가치를 납득할 수 있도록 정보 중심의 긴 호흡으로 레이아웃을 설계했습니다.</p><img src="${a.image}" alt="덴클 공식몰 상세페이지 구성"><p class="image-caption"><a href="${a.image}" data-enlarge>공식몰 이미지 크게 보기 ↗</a></p></article><article class="study-panel"><span class="eyebrow">02 / KAKAO GIFT</span><h3>시선을 사로잡는 감성적인 페이지</h3><p>선물을 고를 때는 '얼마나 예쁘고 센스 있는지'가 우선입니다. 모바일에서 빠르게 스크롤하는 환경을 고려해 복잡한 텍스트는 과감히 덜어냈습니다. 대신, 고급스러운 패키지와 감각적인 분위기의 이미지를 상단에 집중 배치해, 짧은 시간 안에 선물의 매력을 직관적으로 느끼도록 구성했습니다.</p><img src="${b.image}" alt="덴클 카카오 선물하기 상세페이지 구성"><p class="image-caption"><a href="${b.image}" data-enlarge>선물하기 이미지 크게 보기 ↗</a></p></article></div>`)+section('같은 제품 정보를, 다른 우선순위로.',`<div class="change-points"><div><span>01 — INFORMATION</span><h3>정보의 깊이</h3><p>공식몰에서는 기술과 성분을 충분히 설명하고, 선물하기에서는 핵심 정보를 선별했습니다.</p></div><div><span>02 — VISUAL</span><h3>비주얼의 역할</h3><p>기술의 신뢰를 전달하는 정보형 구성과 선물의 매력을 보여주는 패키지 중심 구성을 구분했습니다.</p></div><div><span>03 — CONTEXT</span><h3>고객의 탐색 맥락</h3><p>제품을 검토하는 구매와 선물을 고르는 구매에 맞춰, 먼저 보여줄 내용을 달리했습니다.</p></div></div>`);}
  function renewalStudy(){const w=byKey.connectKinloch;return head('FASHION / WEB DESIGN · 실무 프로젝트',names.connectKinloch,w.summary)+facts([['브랜드','커넥트킨록 / 원풍물산'],['담당','기존 페이지 진단 · 정보 우선순위 · 레이아웃'],['참여 범위','레이아웃 재설계 · 촬영/디테일 이미지 선별 100%']])+section('제품을 충분히 볼 수 있는 화면으로.',`<p>분절된 구성과 좁은 여백을 정리하고, 착용 컷과 소재 디테일을 확대했습니다. 무엇을 먼저 보고 어떤 정보를 이어 읽을지에 집중했습니다.</p><div class="before-after-controls" role="group" aria-label="리뉴얼 전후 선택"><button type="button" data-comparison="after" aria-pressed="true">개선 후</button><button type="button" data-comparison="before" aria-pressed="false">개선 전</button></div><div class="large-work"><img id="renewal-image" src="${w.image}" alt="커넥트킨록 상세페이지 개선 후"></div><p class="image-caption"><a id="renewal-original" href="${w.image}" data-enlarge>선택한 이미지 크게 보기 ↗</a></p>`)+section('개선의 기준',`<div class="change-points"><div><span>01 — HIERARCHY</span><h3>착용 이미지 우선</h3><p>실루엣과 핏을 먼저 파악할 수 있도록 모델 착용 컷의 비중을 높였습니다.</p></div><div><span>02 — DETAIL</span><h3>소재를 더 선명하게</h3><p>질감과 제품 디테일을 충분한 크기로 배치해 이미지에서 정보를 읽도록 구성했습니다.</p></div><div><span>03 — RHYTHM</span><h3>읽는 순서 정리</h3><p>여백과 타이포그래피를 정돈해 이미지 감상에서 제품 정보 확인으로 자연스럽게 이어지도록 했습니다.</p></div></div>`);}
  function fashionStudy(){return head('FASHION / CONTENT & PROMOTION · 실무 프로젝트','브랜드의 무드를 일상의 콘텐츠로','에든버러클럽의 클래식한 분위기를 SNS 스타일링 콘텐츠와 공식몰 시즌 프로모션에 적용했습니다. 콘텐츠의 목적에 맞춰 이미지와 메시지의 비중을 조정한 작업들을 함께 소개합니다.')+facts([['브랜드','에든버러클럽 / 원풍물산'],['담당','SNS 콘텐츠 · 공식몰 프로모션 배너'],['디자인 방향','클래식한 브랜드 톤 · 명확한 메시지']])+['edinburghCardNews','summerBanner','seasonOffBanner'].map(key=>{const w=byKey[key];return section(names[key],`<p>${esc(w.summary)}</p>`+image(w.image,w.alt));}).join('');}
  function singleStudy(w){const personal=w.personal?'개인 프로젝트':'실무 프로젝트';let body=head(`${typeNames[w.type]||w.category} / ${personal}`,title(w),w.summary)+facts([['구분',w.category],['담당 / 제작 범위',plain(w.project||w.concept||'')],['프로젝트',personal+(w.type==='visual'?' · AI 생성 비주얼':'')]]);if(w.key==='pinkHaloTintLaunch'){body+=section('제품의 컬러가 기억되는 런칭 화면',`<p>색조 브랜드의 신상품 출시를 가정한 개인 프로젝트입니다. 틴트명, 컬러 라인업, 모델 이미지와 배너 레이아웃을 함께 구성했습니다. 모델 이미지는 AI를 활용해 제작했습니다.</p>`+image(w.image,w.alt,'가상 신제품 출시 시안 · 실제 브랜드 의뢰 또는 집행 성과를 의미하지 않습니다.'));body+=section('디자인 포인트',`<div class="change-points"><div><span>01 — COLOR</span><h3>제품과 무드의 연결</h3><p>핑크 톤과 글로시한 메이크업 이미지로 밝고 가벼운 제품 분위기를 표현했습니다.</p></div><div><span>02 — PRODUCT</span><h3>컬러 라인업 구성</h3><p>제품명과 발색 컬러를 한 화면에서 비교할 수 있도록 배치했습니다.</p></div><div><span>03 — LAYOUT</span><h3>출시 메시지의 우선순위</h3><p>모델 이미지, 제품명, 컬러 정보의 위계를 구분해 신상품의 인상을 전달했습니다.</p></div></div>`);}else{body+=section(w.comparisonLayout?'촬영 원본과 보정 결과':'디자인 결과',image(w.image,w.alt,w.personal?'개인 제작 시안 · AI 활용 범위는 아래 제작 내용에 기재했습니다.':''));const fields=[['제품 / 목적',w.product],['콘셉트',w.concept],['제작 / 참여 범위',w.project],['타깃 / 결과',w.target]].filter(([,v])=>v);body+=section('프로젝트 노트',`<div class="change-points">${fields.map(([k,v])=>`<div><h3>${esc(k)}</h3><p>${esc(plain(v))}</p></div>`).join('')}</div>`);}return body;}
  function showProject(key){if(!byKey[key]&&!['channel','fashionContent'].includes(key)){if(dialog.open)closeVisual();return;}if(!dialog.open){returnFocus=document.activeElement;dialog.showModal();document.body.classList.add('modal-open');}const body=key==='channel'?channelStudy():key==='connectKinloch'?renewalStudy():key==='fashionContent'?fashionStudy():singleStudy(byKey[key]);content.innerHTML=`<article class="detail-wrap">${body}<div class="detail-end"><a href="#selected">← 대표 프로젝트로</a><a href="mailto:8403ss@naver.com">프로젝트 이야기 나누기 ↗</a></div></article>`;dialog.scrollTop=0;document.title=`${key==='channel'?'채널별 상세페이지':key==='fashionContent'?'패션 콘텐츠':title(byKey[key])} — 권혜지`;content.querySelector('h1').focus({preventScroll:true});content.querySelectorAll('[data-comparison]').forEach(b=>b.addEventListener('click',()=>{const before=b.dataset.comparison==='before';const w=byKey.connectKinloch;const img=document.getElementById('renewal-image');img.src=before?w.beforeImage:w.image;img.alt=`커넥트킨록 상세페이지 ${before?'개선 전':'개선 후'}`;document.getElementById('renewal-original').href=img.src;content.querySelectorAll('[data-comparison]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));}
  function closeVisual(){if(viewer.open)viewer.close();dialog.close();document.body.classList.remove('modal-open');document.title='권혜지 — Web & Content Designer';returnFocus?.focus({preventScroll:true});}
  function closeProject(){if(openedFromPage){history.back();}else{location.hash=returnHash;}openedFromPage=false;}
  document.addEventListener('click',e=>{const link=e.target.closest('a[href^="#project/"]');if(link&&!dialog.open){returnHash=location.hash&&!location.hash.startsWith('#project/')?location.hash:'#selected';openedFromPage=true;}});
  function route(){if(location.hash.startsWith('#project/'))showProject(decodeURIComponent(location.hash.slice(9)));else if(dialog.open)closeVisual();}
  document.getElementById('close-project').addEventListener('click',closeProject);dialog.addEventListener('cancel',e=>{e.preventDefault();closeProject();});window.addEventListener('hashchange',route);route();

  const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  if('IntersectionObserver' in window&&!reduced.matches){document.documentElement.classList.add('motion-ready');const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));}
  const reel=document.querySelector('.work-reel'),intro=document.querySelector('.intro-scene');
  const tracks=[...document.querySelectorAll('.reel-track')],copyLines=[...document.querySelectorAll('.scroll-copy span')],stackCards=[...document.querySelectorAll('.rolling-project')];
  let ticking=false;
  const clamp=n=>Math.min(1,Math.max(0,n));
  function updateScroll(){
    const vh=window.innerHeight;
    const reelProgress=clamp((vh-reel.getBoundingClientRect().top)/(vh+reel.offsetHeight));
    tracks.forEach((track,i)=>track.style.setProperty('--reel-x',(reduced.matches?0:(reelProgress-.5)*(i?-220:220))+'px'));
    const introProgress=clamp(-intro.getBoundingClientRect().top/Math.max(1,intro.offsetHeight-intro.querySelector('.intro-sticky').offsetHeight));
    copyLines.forEach((line,i)=>line.style.setProperty('--line-opacity',reduced.matches?1:.3+.7*clamp((introProgress*copyLines.length-i+1))));
    const stackEnabled=!reduced.matches&&vh>=720&&innerWidth>=700;
    stackCards.forEach((card,i)=>{const next=stackCards[i+1];const progress=next?clamp((vh-next.getBoundingClientRect().top)/(vh-80)):0;card.style.setProperty('--stack-scale',stackEnabled?1-progress*.045:1);card.style.setProperty('--stack-shade',stackEnabled?1-progress*.05:1);});
    ticking=false;
  }
  function queueScroll(){if(!ticking){requestAnimationFrame(updateScroll);ticking=true;}}
  reduced.addEventListener('change',queueScroll);window.addEventListener('scroll',queueScroll,{passive:true});window.addEventListener('resize',queueScroll);updateScroll();
})();
