window.PORTFOLIO_WORKS = [
  {
    "key": "toothbrushGlobal",
    "type": "detail",
    "category": "상세페이지",
    "title": "Global Toothbrush Detail Page",
    "image": "assets/detail_01_toothbrush.webp",
    "alt": "Dencle toothbrush detail page",
    "summary": "특허 구조와 제품 기능을 해외 소비자가 빠르게 이해할 수 있도록, 복잡한 기술 정보를 인포그래픽과 다이어그램 중심의 구매 흐름으로 재구성한 글로벌 상세페이지입니다.",
    "product": "특허받은 칫솔 구조와 기능 정보가 복잡해 제품 차별점을 짧은 시간 안에 이해하기 어려움",
    "concept": "정보 구조 설계, 인포그래픽·다이어그램 제작, 상세페이지 비주얼 디자인 100% (텍스트 제외)",
    "project": "핵심 기술 우선순위 정리 > 기능별 시각화 > 글로벌·모바일 가독성 기준으로 섹션 재구성",
    "target": "제품 구조, 사용 효과, 신뢰 근거가 한 흐름으로 연결되어 핵심 차별점을 빠르게 비교·이해할 수 있는 페이지 완성",
    "labels": {
      "product": "Problem",
      "concept": "Role",
      "project": "Process",
      "target": "Outcome"
    }
  },
  {
    "key": "granuleOfficial",
    "type": "detail",
    "category": "상세페이지",
    "title": "Tooth Granule · Official Store",
    "image": "assets/detail_02_toothgranule_official.webp",
    "alt": "Dencle tooth granule official detail page",
    "summary": "공식몰 고객이 프리미엄 제품의 기술력과 성분을 충분히 검토할 수 있도록, 특허 공법·인증·제품 정보를 긴 호흡의 설득 구조로 설계한 공식 홈페이지용 상세페이지입니다.",
    "product": "고가의 신개념 가루치약을 구매하기 전 제형, 특허 기술, 성분 안정성에 대한 충분한 정보와 신뢰 형성이 필요",
    "concept": "제품 정보 구조, 섹션 설계, 키 비주얼·인포그래픽, 상세페이지 디자인 100% (텍스트 제외)",
    "project": "브랜드 신뢰 형성 > 특허 공법과 성분 정보 확장 > 인증·효능 근거 제시 > 제품 선택 정보로 연결",
    "target": "검색·유입 고객이 제품 이해부터 신뢰 형성, 구매 검토까지 단계적으로 이어갈 수 있는 공식몰용 정보 중심 페이지 완성",
    "labels": {
      "product": "Problem",
      "concept": "Role",
      "project": "Process",
      "target": "Outcome"
    }
  },
  {
    "key": "granule",
    "type": "detail",
    "category": "상세페이지",
    "title": "Tooth Granule · Kakao Gift",
    "image": "assets/detail_03_toothgranule_kakao.webp",
    "alt": "Dencle tooth granule gift detail page",
    "summary": "동일한 그래뉼 치약을 카카오톡 선물하기 고객의 짧은 탐색 흐름에 맞춰 재편한 상세페이지입니다. 공식몰보다 정보량을 줄이고 선물 가치, 패키지, 감성 비주얼을 우선 배치했습니다.",
    "product": "브랜드 사전 지식이 적은 선물 구매자가 짧은 탐색 안에 제품 매력과 선물 가치를 판단해야 함",
    "concept": "플랫폼 특성 분석, 정보 선별, 비주얼 콘셉트·레이아웃, 상세페이지 디자인 100% (텍스트 제외)",
    "project": "공식몰 정보 선별 > 선물 패키지와 감성 이미지 우선 노출 > 모바일 속도에 맞춘 짧고 직관적인 섹션 구성",
    "target": "동일 제품을 플랫폼 맥락에 맞게 감성·패키지·핵심 효능 중심으로 재설계해 선물 구매 흐름에 최적화",
    "labels": {
      "product": "Problem",
      "concept": "Role",
      "project": "Process",
      "target": "Outcome"
    }
  },
  {
    "key": "connectKinloch",
    "type": "detail",
    "category": "패션 브랜드 상세페이지 개선",
    "title": "Connect Kinloch · Detail Page Renewal",
    "image": "assets/detail_04_connect_kinloch.webp",
    "beforeImage": "assets/detail_04_connect_kinloch_before.png",
    "alt": "Connect Kinloch menswear detail page",
    "summary": "기존 상세페이지의 정보 밀도와 작은 이미지 문제를 개선해, 모델 착용 컷과 소재 디테일이 먼저 읽히도록 구매 흐름을 재설계한 남성복 상세페이지 리뉴얼입니다.",
    "product": "분절된 레이아웃과 좁은 여백으로 제품 실루엣, 소재 텍스처, 핵심 정보의 우선순위가 명확하지 않음",
    "concept": "기존 페이지 진단, 정보 우선순위 및 레이아웃 재설계, 촬영·디테일 이미지 선별 100%",
    "project": "기존·경쟁 페이지 분석 > 모바일 정보 구조 정리 > 착용·소재 디테일 확대 > 여백과 타이포 체계 개선",
    "target": "제품 이해와 구매 검토 흐름을 개선했으며, 리뉴얼 적용 후 동기간 대비 유입량과 판매량 상승을 확인",
    "labels": {
      "product": "Problem",
      "concept": "Role",
      "project": "Process",
      "target": "Outcome"
    }
  },
  {
    "key": "edinburghClub",
    "type": "detail",
    "category": "상세페이지",
    "title": "Edinburgh Club · Product Page",
    "image": "assets/detail_05_edinburgh_club.webp",
    "alt": "Edinburgh Club menswear detail page",
    "summary": "브리티시 클래식 무드의 니트웨어를 촬영 이미지와 소재 디테일 중심으로 풀어내고, 컬러·사이즈·케어 정보를 차분하게 정리하여 프리미엄 소재감과 브랜드 감성을 전달한 남성복 상세페이지입니다.",
    "product": "(주)원풍물산 에든버러클럽",
    "concept": "브리티시 헤리티지와 클래식한 니트 조직감을 강조한 차분하고 고급스러운 프리미엄 캐주얼 무드",
    "project": "1인 100% (텍스트 제외)",
    "target": "프리미엄 소재 및 디테일 중시 소비자 / 무신사&29cm 이용 고객"
  },
  {
    "key": "portraitRetouch",
    "type": "retouch",
    "category": "촬영본 보정 & 리터치",
    "title": "인물 피부 보정",
    "image": "assets/retouch_01_portrait.png",
    "alt": "인물 촬영 원본과 보정본 비교",
    "summary": "",
    "product": "Adobe Photoshop",
    "concept": "",
    "project": "",
    "target": "",
    "comparisonLayout": true,
    "labels": {
      "product": "Tool"
    }
  },
  {
    "key": "portraitRetouch02",
    "type": "retouch",
    "category": "촬영본 보정 & 리터치",
    "title": "인물 피부·톤 보정",
    "image": "assets/retouch_02_korean_portrait.png",
    "alt": "한국인 남성 인물 촬영 원본과 보정본 비교",
    "summary": "",
    "product": "Adobe Photoshop",
    "concept": "",
    "project": "",
    "target": "",
    "comparisonLayout": true,
    "comparisonY": "-19%",
    "labels": {
      "product": "Tool"
    }
  },
  {
    "key": "portraitRetouch03",
    "type": "retouch",
    "category": "촬영본 보정 & 리터치",
    "title": "배경·얼굴·의상 보정",
    "image": "assets/retouch_03_foreign_portrait.png",
    "alt": "외국인 남성 인물 촬영 원본과 보정본 비교",
    "summary": "",
    "product": "Adobe Photoshop",
    "concept": "배경 · 얼굴 · 의상 보정",
    "project": "",
    "target": "",
    "comparisonLayout": true,
    "comparisonY": "-10.2%",
    "labels": {
      "product": "Tool",
      "concept": "Retouch"
    }
  },
  {
    "key": "garmentRetouch01",
    "type": "retouch",
    "category": "촬영본 보정 & 리터치",
    "title": "베이지 팬츠 주름 보정",
    "image": "assets/retouch_04_beige_pants.png",
    "alt": "베이지 팬츠 촬영 원본과 주름 보정본 비교",
    "summary": "",
    "product": "Adobe Photoshop",
    "concept": "주름 보정",
    "project": "",
    "target": "",
    "comparisonLayout": true,
    "comparisonY": "-19%",
    "labels": {
      "product": "Tool",
      "concept": "Retouch"
    }
  },
  {
    "key": "garmentRetouch02",
    "type": "retouch",
    "category": "촬영본 보정 & 리터치",
    "title": "블랙 팬츠 주름 보정",
    "image": "assets/retouch_05_black_pants.png",
    "alt": "블랙 팬츠 촬영 원본과 주름 보정본 비교",
    "summary": "",
    "product": "Adobe Photoshop",
    "concept": "주름 보정",
    "project": "",
    "target": "",
    "comparisonLayout": true,
    "comparisonY": "-19%",
    "labels": {
      "product": "Tool",
      "concept": "Retouch"
    }
  },
  {
    "key": "brochureGranule",
    "type": "print",
    "category": "홍보 자료 / 인쇄물",
    "title": "Patent Technology Brochure",
    "image": "assets/print_01_patent_tech_brochure.webp",
    "alt": "Dencle patented technology brochure",
    "summary": "덴클의 특허 기술인 그래뉼 공법과 컬러체인지 기술의 차별점을 직관적으로 전달하기 위해 클린하고 모던한 톤을 적용한 브로슈어입니다. 그린 컬러와 인포그래픽을 활용해 기술적 신뢰성과 혁신성을 강조하고, 화이트 기반 섹션 분리로 가독성을 높였습니다.",
    "product": "덴클 그래뉼치약",
    "concept": "특허 기술의 신뢰성과 혁신성을 강조한 클린 & 프로페셔널 디자인",
    "project": "1인 100% (텍스트 제외)",
    "target": "그래뉼 공법을 처음 접하는 소비자 및 바이어"
  },
  {
    "key": "brochureToothbrush",
    "type": "print",
    "category": "홍보 자료 / 인쇄물",
    "title": "Toothbrush Brochure",
    "image": "assets/print_02_toothbrush_brochure.webp",
    "alt": "Dencle three toothbrush line brochure",
    "summary": "덴클 칫솔 프리미엄 라인의 기능적 차별성과 구조적 특장점을 전달하기 위해 모노톤 기반의 전문적인 톤앤매너로 구성한 브로슈어입니다. 특허 구조, 항균 테스트, FDA 승인, 수상 이력 등을 함께 배치해 글로벌 시장에서도 제품 신뢰도가 느껴지도록 설계했습니다.",
    "product": "덴클 칫솔 프리미엄 라인",
    "concept": "글로벌 바이어를 위한 전문성과 제품력 시각화 / 덴클 전용 특허 칫솔 구조의 직관적 전달",
    "project": "1인 100% (텍스트 제외)",
    "target": "외국 기업 바이어 / 제품 검토 담당자"
  },
  {
    "key": "productIntro",
    "type": "print",
    "category": "홍보 자료 / 인쇄물",
    "title": "Tooth Granule Product Deck",
    "image": "assets/print_03_toothgranule_deck.webp",
    "alt": "Dencle tooth granule product introduction deck",
    "summary": "덴클 그래뉼 치약을 소개하는 제품소개서로, 브랜드 소개에서 특허 기술, 세부 제품군까지 이어지는 정보 흐름을 설계했습니다. 인포그래픽과 아이콘을 활용해 그래뉼 공법과 컬러체인지 기술의 차별점을 직관적으로 보여주고, 처음 접하는 거래처도 제품력을 쉽게 이해하도록 구성했습니다.",
    "product": "덴클 가루 치약",
    "concept": "브랜드 신뢰도와 제품 기술력을 단계적으로 이해시키는 세일즈형 제품소개서",
    "project": "1인 100% (텍스트 제외)",
    "target": "바이어 / 거래처 / 제품을 처음 접하는 파트너사"
  },
  {
    "key": "edinburghCompanyDeck",
    "type": "print",
    "category": "홍보 자료 / 인쇄물",
    "title": "Edinburgh Company Deck",
    "image": "assets/print_04_edinburgh_company_deck.webp",
    "alt": "Kinloch Anderson Edinburgh company introduction deck",
    "summary": "킨록앤더슨 에든버러클럽의 브리티시 헤리티지와 클래식한 브랜드 정체성을 전달하기 위해, 아카이브 이미지와 타탄 패턴, 빈티지한 종이 질감을 활용한 회사소개서입니다. 브랜드의 역사와 제품 디테일이 함께 읽히도록 구성해 바이어가 브랜드의 무드와 상품성을 동시에 이해할 수 있도록 설계했습니다.",
    "product": "킨록앤더슨 에든버러클럽",
    "concept": "브리티시 아카이브와 클래식 헤리티지를 강조한 프리미엄 브랜드 소개서",
    "project": "1인 100% (텍스트 제외)",
    "target": "바이어 / 거래처 / 클래식 남성복 브랜드를 검토하는 파트너사",
    "labels": {
      "product": "Brand",
      "concept": "Concept",
      "project": "Project",
      "target": "Target"
    }
  },
  {
    "key": "connectKinlochProposal",
    "type": "print",
    "category": "홍보 자료 / 인쇄물",
    "title": "Connect Kinloch Proposal",
    "image": "assets/print_05_connect_kinloch_proposal.webp",
    "alt": "Connect Kinloch company proposal deck",
    "summary": "커넥트킨록의 성장 지표, 룩북 이미지, 핵심 상품군, 브랜드 포지셔닝을 한눈에 보여주기 위해 제작한 사업제안서형 회사소개서입니다. 플랫폼 MD와 바이어가 브랜드의 현재 성과와 판매 가능성을 빠르게 판단할 수 있도록 그래프, 룩북, 상품 정보를 명확한 구조로 정리했습니다.",
    "product": "커넥트킨록",
    "concept": "컨템포러리 남성복 브랜드의 성장성과 상품 경쟁력을 설득하는 플랫폼 제안형 디자인",
    "project": "1인 100% (텍스트 제외)",
    "target": "플랫폼 MD / 바이어 / 입점 및 협업을 검토하는 비즈니스 파트너",
    "labels": {
      "product": "Brand",
      "concept": "Concept",
      "project": "Project",
      "target": "Target"
    }
  },
  {
    "key": "birthdayEvent",
    "type": "event",
    "category": "프로모션 / 이벤트",
    "title": "Dencle 10th Anniversary",
    "image": "assets/event_01_birthday_10th.webp",
    "alt": "10th birthday event page",
    "summary": "덴클 10주년을 맞아 브랜드 스토리와 고객 감사 혜택을 모바일 스크롤 흐름에 맞춰 구성한 이벤트 페이지입니다. 럭키박스와 100원딜, 쿠폰 혜택을 그래픽 요소와 명확한 CTA로 연결해 참여 기대감을 높였습니다.",
    "product": "브랜드 10주년 기념 및 고객 감사 프로모션",
    "concept": "축제 분위기를 강조한 직관적 디자인 / 구강케어 브랜드에 맞는 청결한 블루·화이트 컬러 톤",
    "project": "1인 100% (텍스트 제외)",
    "target": "덴클 기존 고객 / 신규 유입 고객",
    "labels": {
      "product": "Event Purpose",
      "concept": "Concept",
      "project": "Project",
      "target": "Target"
    }
  },
  {
    "key": "summerEvent",
    "type": "event",
    "category": "프로모션 / 이벤트",
    "title": "Summer Promotion Page",
    "image": "assets/event_02_summer_page.webp",
    "alt": "Summer event page",
    "summary": "덴클 여름 프로모션 이벤트 페이지는 수영장 패턴과 모래사장 그래픽을 활용해 계절감을 직관적으로 전달하고, 할인 혜택과 신규 가입 혜택이 단계적으로 읽히도록 구성한 모바일 중심 이벤트 페이지입니다.",
    "product": "여름철 특별 혜택 제공을 통해 브랜드 친밀도와 신규 유입을 높이는 프로모션",
    "concept": "여름 바캉스의 시원한 무드 / 블루 톤과 해변 요소를 활용한 청량감 강조",
    "project": "1인 100% (텍스트 제외)",
    "target": "덴클 기존 고객 / 신규 유입 고객",
    "labels": {
      "product": "Event Purpose",
      "concept": "Concept",
      "project": "Project",
      "target": "Target"
    }
  },
  {
    "key": "summerBanner",
    "type": "event",
    "category": "프로모션 / 이벤트",
    "title": "Summer Promotion Banner",
    "image": "assets/event_03_summer_banner.webp",
    "alt": "Edinburgh Club summer promotion official mall banner",
    "summary": "에든버러클럽의 차분한 촬영 이미지와 공식몰 UI 흐름을 유지하면서, 여름 시즌 할인 메시지가 메인 화면에서 자연스럽게 보이도록 구성한 빅배너 디자인입니다.",
    "product": "공식몰 메인 영역에서 시즌 프로모션과 신상품 유입을 동시에 유도",
    "concept": "클래식하고 담백한 브랜드 무드에 여름 할인 메시지를 얹은 룩북형 배너 구성",
    "project": "1인 100%",
    "target": "에든버러클럽 공식몰 방문자 / 클래식 캐주얼 관심 소비자",
    "labels": {
      "product": "Event Purpose",
      "concept": "Concept",
      "project": "Project",
      "target": "Target"
    }
  },
  {
    "key": "seasonOffBanner",
    "type": "event",
    "category": "프로모션 / 이벤트",
    "title": "Season-Off Banner",
    "image": "assets/event_04_season_off_banner.webp",
    "alt": "Edinburgh Club season off official mall banner",
    "summary": "간절기 무드가 느껴지는 어두운 톤의 룩북 이미지를 중심으로, 시즌오프 세일 메시지가 과하게 튀지 않으면서도 즉시 인지되도록 설계한 공식몰 빅배너입니다.",
    "product": "시즌 전환 시점의 세일 주목도와 상품 유입을 높이는 프로모션 배너",
    "concept": "남성복 브랜드의 클래식한 분위기를 유지한 절제된 톤 / 계절 전환감을 담은 이미지 중심 구성",
    "project": "1인 100%",
    "target": "에든버러클럽 공식몰 방문자 / 시즌오프 혜택을 찾는 남성복 소비자",
    "labels": {
      "product": "Event Purpose",
      "concept": "Concept",
      "project": "Project",
      "target": "Target"
    }
  },
  {
    "key": "chuseokBigSale",
    "type": "event",
    "category": "프로모션 / 이벤트",
    "title": "Chuseok Big Sale",
    "image": "assets/event_05_chuseok_big_sale.webp",
    "alt": "Kinloch by Kinloch Anderson Chuseok big sale banner",
    "summary": "킨록 바이 킨록앤더슨의 안정적인 남성복 이미지를 유지하면서, 추석 시즌의 따뜻한 색감과 낙엽 그래픽을 더해 명절 프로모션임을 직관적으로 전달한 빅세일 배너입니다.",
    "product": "추석 시즌 매출 증대와 네이버 스토어 프로모션 유입 강화",
    "concept": "중장년 남성 고객도 빠르게 이해할 수 있는 명확한 행사명 / 따뜻한 베이지 톤과 시즌 그래픽을 활용한 실속형 프로모션 무드",
    "project": "1인 100%",
    "target": "킨록 바이 킨록앤더슨의 클래식 남성복을 찾는 3040-50대 남성 고객 / 명절 선물 및 실속 구매층",
    "labels": {
      "product": "Event Purpose",
      "concept": "Concept",
      "project": "Project",
      "target": "Target"
    }
  },
  {
    "key": "instagramFeed",
    "type": "sns",
    "category": "SNS / 디지털 콘텐츠",
    "title": "Dencle Instagram Feed",
    "image": "assets/sns_01_dencle_moodboard.webp",
    "alt": "Dencle Instagram feed mood board",
    "summary": "화이트 배경을 중심으로 깔끔한 레이아웃을 구성하고, 제품 컬러를 포인트로 사용해 SNS 환경에서도 기능과 인증 정보가 빠르게 전달되도록 정리한 피드 디자인입니다.",
    "product": "덴클 칫솔, 혀클리너",
    "concept": "화이트 톤과 미니멀한 구성으로 위생 제품의 청결함과 신뢰감을 강조",
    "project": "1인 100%",
    "target": "2030 실용 소비자층"
  },
  {
    "key": "kinlochMoodBoard",
    "type": "sns",
    "category": "SNS / 디지털 콘텐츠",
    "title": "Connect Kinloch Mood Board",
    "image": "assets/sns_02_kinloch_moodboard.webp",
    "alt": "Connect Kinloch Instagram mood board",
    "summary": "커넥트킨록의 컨템포러리 캐주얼 무드를 시각적으로 정리하기 위해 그린, 레드, 뉴트럴 톤의 레퍼런스를 조합하고, 룩과 소재감이 함께 보이도록 구성한 인스타그램 무드보드입니다.",
    "product": "(주)원풍물산 커넥트킨록",
    "concept": "컨템포러리 캐주얼 & 깔끔한 브랜드 무드",
    "project": "1인 100%",
    "target": "2030 남성복 관심층 / 브랜드 무드를 빠르게 확인하는 SNS 유저"
  },
  {
    "key": "edinburghCardNews",
    "type": "sns",
    "category": "SNS / 디지털 콘텐츠",
    "title": "Winter Office Styling Content",
    "image": "assets/sns_03_edinburgh_cardnews.webp",
    "alt": "Edinburgh Club fashion card news",
    "summary": "에든버러클럽의 클래식한 겨울 오피스룩을 셔츠, 니트, 수트 조합 중심으로 풀어내고, 스타일링 팁을 함께 배치해 SNS 안에서도 정보성과 브랜드 무드가 동시에 전달되도록 구성한 카드뉴스입니다.",
    "product": "(주)원풍물산 에든버러클럽",
    "concept": "클래식 오피스웨어와 브리티시 헤리티지를 기반으로 한 실용적인 스타일링 제안",
    "project": "1인 100%",
    "target": "스타일링 정보를 원하는 SNS 유저 / 클래식 캐주얼 관심 소비자"
  },
  {
    "key": "edinburghEventInfo",
    "type": "sns",
    "category": "SNS / 디지털 콘텐츠",
    "title": "에든버러클럽 클리어런스세일 카드뉴스",
    "image": "assets/sns_05_edinburgh_event.webp",
    "alt": "에든버러클럽 클리어런스세일 카드뉴스",
    "summary": "무신사 클리어런스 세일 정보를 제품 카드 형태로 정리하고, 메모지와 클립 요소를 활용해 행사성을 더하면서도 에든버러클럽의 클래식한 제품 이미지가 깔끔하게 보이도록 구성한 이벤트 콘텐츠입니다.",
    "product": "(주)원풍물산 에든버러클럽",
    "concept": "화이트 카드 레이아웃과 제품 중심 구성으로 세일 정보를 직관적으로 전달하는 깔끔한 이벤트 무드",
    "project": "1인 100%",
    "target": "2030 젊은 소비층 / SNS에서 행사 정보를 확인하는 유저"
  },
  {
    "key": "influencerSponsorship",
    "type": "sns",
    "category": "SNS / 디지털 콘텐츠",
    "title": "Influencer Styling Content",
    "image": "assets/sns_07_influencer_sponsorship.webp",
    "alt": "Connect Kinloch influencer sponsorship styling content",
    "summary": "인플루언서 착용 이미지를 활용해 실제 코디 흐름과 제품 스타일링 포인트를 보여주는 SNS 콘텐츠입니다. 일상 사진 안에서 아이템의 핏과 무드를 자연스럽게 전달하도록 구성했습니다.",
    "product": "(주)원풍물산 커넥트킨록",
    "concept": "실착 기반의 다양한 코디법 전달 / 자연스러운 착용 무드와 스타일링 정보 제공",
    "project": "1인 100%",
    "target": "SNS 이용자 / 실착 스타일링을 참고하는 2030 소비자"
  },
  {
    "key": "visualAi13",
    "type": "sns",
    "category": "SNS / 디지털 콘텐츠",
    "title": "Hydration Ampoule Ad",
    "image": "assets/visual_ai_13.jpg",
    "alt": "Medipeel hydration ampoule beauty advertisement design using AI generated background",
    "summary": "수분감 있는 블루 톤의 AI 생성 배경을 기반으로, 앰플 제품의 효능 키워드와 정보 구조를 직접 배치한 뷰티 디지털 광고 시안입니다. SNS 피드, 브랜드 마케팅 배너, 상세페이지 키 비주얼로 확장할 수 있도록 제품명과 핵심 베네핏이 빠르게 읽히는 구조로 디자인했습니다.",
    "product": "뷰티 앰플 디지털 광고 콘텐츠",
    "concept": "AI 생성 배경을 활용한 수분감 중심의 코스메틱 SNS 배너 디자인",
    "project": "배경 AI 생성 / 제품 정보 구조, 타이포그래피, 레이아웃 직접 작업",
    "target": "뷰티 브랜드 SNS 광고 유저 / 상세페이지 유입 고객",
    "personal": true
  },
  {
    "key": "pinkHaloTintLaunch",
    "type": "sns",
    "category": "SNS / 디지털 콘텐츠",
    "title": "Pink Halo Tint Launch",
    "image": "assets/sns_09_pink_halo_tint.png",
    "alt": "Pink Halo Aura Tint new product launch banner",
    "summary": "색조 브랜드 신상품 출시를 가정해 제작한 런칭 배너 및 광고 이미지입니다. 틴트명, 컬러 라인업, 모델 이미지까지 함께 기획해 핑크 톤의 밝고 러블리한 분위기를 만들고, 플랫폼 메인 배너나 SNS 광고에서 신제품의 컬러감을 빠르게 인지할 수 있도록 구성했습니다.",
    "product": "Pink Halo Aura Tint 신상품 출시 배너",
    "concept": "핑크 무드와 글로시한 메이크업 이미지를 중심으로 한 색조 브랜드 런칭 비주얼",
    "project": "틴트명 기획 / 모델 이미지 제작 / 컬러 라인업 구성 / 배너 레이아웃 디자인",
    "target": "신상품 색조 제품을 탐색하는 10대 후반~30대 뷰티 소비자 / 뷰티 플랫폼 및 SNS 이용자",
    "personal": true
  },
  {
    "key": "onairDisplay",
    "type": "offline",
    "category": "Offline",
    "title": "On-air Display",
    "image": "assets/onair_display.jpg",
    "alt": "Home shopping on-air display",
    "summary": "홈쇼핑 방송 환경에서 제품과 브랜드가 즉시 인지되도록 구성한 오프라인 디스플레이입니다.",
    "purpose": "방송 화면과 현장 동선에서 제품 존재감 강화",
    "point": "제품 스케일, 패키지 컬러, 브랜드 로고 노출을 고려한 공간 비주얼",
    "role": "Visual direction / print and production support"
  },
  {
    "key": "hostPanel",
    "type": "offline",
    "category": "Offline",
    "title": "Host Panel",
    "image": "assets/host_panels.jpg",
    "alt": "Home shopping host panels",
    "summary": "쇼호스트가 방송 중 핵심 혜택과 제품 정보를 빠르게 전달할 수 있도록 만든 핸드 패널입니다.",
    "purpose": "혜택, 가격, 제품 특징을 방송 화면에서 즉시 읽히게 구성",
    "point": "강한 대비, 짧은 문장, 화면 노출을 고려한 글자 크기와 정보 밀도",
    "role": "Visual design 100% / text planning with MD direction"
  },
  {
    "key": "menuBanner",
    "type": "offline",
    "category": "Offline",
    "title": "Cafe Menu Banner",
    "image": "assets/menu_banner.jpg",
    "alt": "Cafe menu banner",
    "summary": "매장 안에서 메뉴와 제품 이미지를 자연스럽게 연결해 보여주는 배너 디자인입니다.",
    "purpose": "방문 고객이 메뉴 정보를 빠르게 인지하도록 돕는 현장용 비주얼 제작",
    "point": "제품 컷, 메뉴 정보, 공간 톤을 맞춘 차분한 배치",
    "role": "Visual design 100%"
  },
  {
    "key": "visualAi01",
    "type": "visual",
    "category": "패션 브랜드 AI 생성 룩북",
    "title": "Editorial Campaign Direction",
    "image": "assets/visual_ai_01.webp",
    "alt": "AI generated soft editorial fashion campaign visual",
    "summary": "자연광과 화이트 아웃핏, 스트라이프 패턴의 조화를 통해 클래식한 시즌 캠페인을 연출한 100% AI 생성 비주얼입니다. 억지스러운 연출을 배제하고 인물 중심의 내추럴한 에디토리얼 룩북 감성을 강조했습니다.",
    "product": "ChatGPT image generation",
    "concept": "시즌 캠페인 에디토리얼 비주얼 제안",
    "project": "크림 화이트 톤, 자연광, 데일리 럭셔리, 빈티지 필름 질감",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi02",
    "type": "visual",
    "category": "패션 브랜드 AI 생성 룩북",
    "title": "Dreamy Portrait Visual",
    "image": "assets/visual_ai_02.webp",
    "alt": "AI generated dreamy fashion portrait visual",
    "summary": "레이스 디테일과 파스텔 코발트 블루, 실내 온카메라 플래시 스냅의 질감을 결합한 100% AI 생성 포트레이트입니다. 페미닌하면서도 몽환적인 무드를 연출하여 브랜드 아카이브 및 SNS 티저 비주얼로 기획했습니다.",
    "product": "ChatGPT image generation",
    "concept": "브랜드 아이덴티티 및 SNS 아카이브 티저 비주얼 제안",
    "project": "파스텔 블루, 레이스 텍스처, 플래시 스냅, 몽환적인 페미닌 무드",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi03",
    "type": "visual",
    "category": "패션 브랜드 AI 생성 룩북",
    "title": "Pastel Product Moodboard",
    "image": "assets/visual_ai_03.webp",
    "alt": "AI generated pastel fashion product styling image",
    "summary": "의류, 슈즈, 가방을 파스텔 톤의 여백 속에 감각적으로 정돈한 100% AI 생성 스타일링 컷입니다. 제품 간의 조화로운 컬러 매칭과 구조적인 레이아웃 구성을 통해 미니멀한 룩북 무드보드를 시각화했습니다.",
    "product": "ChatGPT image generation",
    "concept": "컬렉션 제품 큐레이션 및 룩북 스타일링 무드보드 시각화",
    "project": "파스텔 그린 & 샌드 베이지, 룩북형 콜라주, 미니멀 레이아웃",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi04",
    "type": "visual",
    "category": "패션 브랜드 AI 생성 룩북",
    "title": "Vintage Lookbook Direction",
    "image": "assets/visual_ai_04.webp",
    "alt": "AI generated vintage lookbook fashion visual",
    "summary": "폴라로이드 프레임과 테이핑 디테일, 거친 페이퍼 텍스처를 콜라주하여 빈티지 아카이브 룩북을 재현한 100% AI 생성 작업입니다. 클래식하고 단정한 스타일링 위에 아날로그 질감을 덧대어 차별화된 비주얼을 구성했습니다.",
    "product": "ChatGPT image generation",
    "concept": "브랜드 아카이브 컬렉션 및 아날로그 룩북 방향성 제안",
    "project": "폴라로이드 콜라주, 테이프 텍스처, 소프트 클래식 스타일",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi05",
    "type": "visual",
    "category": "패션 브랜드 AI 생성 룩북",
    "title": "City Chic Campaign Visual",
    "image": "assets/visual_ai_05.webp",
    "alt": "AI generated city chic fashion campaign visual",
    "summary": "모던한 도심 속 거리 배경과 시크한 포즈, 선글라스 및 숄더백의 액세서리 매치를 세련되게 담아낸 100% AI 생성 캠페인 비주얼입니다. 현장감 있는 스냅 촬영 톤으로 컨템포러리 브랜드의 룩북 감성을 극대화했습니다.",
    "product": "ChatGPT image generation",
    "concept": "컨템포러리 브랜드 도심형 룩북 및 캠페인 비주얼 제안",
    "project": "뉴트럴 톤 아웃핏, 모던 시티 스냅, 브라운 레더 매칭",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi06",
    "type": "visual",
    "category": "패션 브랜드 AI 생성 룩북",
    "title": "Beauty Lifestyle Direction",
    "image": "assets/visual_ai_06.webp",
    "alt": "AI generated beauty lifestyle fashion image",
    "summary": "차분한 카페 공간과 내추럴한 아이보리 톤 스타일링을 매치해 뷰티·패션 브랜드의 감도 높은 무드를 보여주는 100% AI 생성 라이프스타일 시안입니다. 상업적인 광고 느낌을 덜어내고 감성적인 일상의 순간을 연출했습니다.",
    "product": "ChatGPT image generation",
    "concept": "감성 라이프스타일 중심의 브랜드 룩북 및 SNS 비주얼 제안",
    "project": "아이보리 & 뉴트럴 컬러, 내추럴 채광, 차분한 데일리 무드",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi11",
    "type": "visual",
    "category": "생성형 AI 활용 광고 이미지",
    "title": "Beauty UGC Mask Visual",
    "image": "assets/visual_ai_11.webp",
    "alt": "AI generated beauty sheet mask selfie visual",
    "summary": "투명한 하이드로겔 시트 마스크와 욕실 거울 셀피 구도를 활용하여 소비자의 내추럴한 사용 컷을 시각화한 100% AI 생성 비주얼입니다. 정제된 스튜디오 컷 대신 친근한 후기 무드로 스킨케어 브랜드의 친밀감을 한층 높였습니다.",
    "product": "ChatGPT image generation",
    "concept": "스킨케어 브랜드의 친근한 리얼 사용 컷 및 UGC 무드 제안",
    "project": "하이드로겔 마스크 팩, 욕실 셀피 스냅, 내추럴 글로우 스킨",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi12",
    "type": "visual",
    "category": "생성형 AI 활용 광고 이미지",
    "title": "Pore Pad Campaign Visual",
    "image": "assets/visual_ai_12.webp",
    "alt": "AI generated beauty pore pad product visual",
    "summary": "강렬한 토너 패드의 디테일을 부드러운 스킨 텍스처와 함께 매칭한 100% AI 생성 뷰티 캠페인 시안입니다. 세련된 상업 조명 아래 수분감 있는 피부 결을 연출하여 효능과 미감을 세련되게 전달합니다.",
    "product": "ChatGPT image generation",
    "concept": "스킨케어 브랜드 제품 패키지 및 텍스처 강조용 캠페인 시안",
    "project": "레드 브랜드 컬러 패키징, 스킨 토너 패드, 맑은 수분 텍스처",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi14",
    "type": "visual",
    "category": "생성형 AI 활용 광고 이미지",
    "title": "Color Makeup Campaign Visual",
    "image": "assets/visual_ai_14.png",
    "alt": "ChatGPT generated color makeup brand advertising visual",
    "summary": "색조 브랜드를 가정해 제작한 AI 광고 이미지입니다. 파스텔 블루 배경과 핑크 톤 립 제품, 글로시한 피부 표현을 조합해 맑고 가벼운 메이크업 무드를 강조했습니다. 제품을 든 인물 중심 구도로 SNS 광고, 캠페인 키 비주얼, 상세페이지 상단 이미지로 확장하기 좋은 뷰티 비주얼을 구성했습니다.",
    "product": "ChatGPT image generation",
    "concept": "색조 브랜드의 촉촉하고 청량한 글로우 메이크업 광고 비주얼",
    "project": "핑크 립 제품, 파스텔 블루 조명, 글로시 스킨, 투명한 색감 중심의 뷰티 캠페인 무드",
    "target": "프롬프트 기획 > 이미지 생성 > 후보정",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  },
  {
    "key": "visualAi15",
    "type": "visual",
    "category": "생성형 AI 활용 광고 이미지",
    "title": "Tint Product Mood Visual",
    "image": "assets/visual_ai_15_muzigae_tint.jpg",
    "alt": "AI reprocessed tint product mood visual based on an existing beauty brand product",
    "summary": "실제 색조 브랜드 제품을 기반으로 AI를 활용해 연출컷을 재가공하고 제작한 제품 무드 비주얼입니다. 투명한 패키지와 핑크 톤의 틴트 제형, 부드러운 조명감을 중심으로 제품의 글로시함과 감성적인 색감을 강조했습니다.",
    "product": "Muzigae Mansion 틴트 제품 무드 비주얼",
    "concept": "실제 브랜드 제품의 패키지 무드를 AI 연출컷으로 재해석한 핑크 톤 뷰티 비주얼",
    "project": "기존 제품 이미지 분석 > AI 연출컷 재가공 및 제작 > 톤 보정",
    "target": "색조 브랜드 캠페인 레퍼런스 / 제품 무드 컷이 필요한 뷰티 마케팅 콘텐츠",
    "labels": {
      "product": "Tool",
      "concept": "Purpose",
      "project": "Direction",
      "target": "Process"
    },
    "personal": true
  }
];
